// last modified 2017-07-29
= Editing Lisp and Scheme files in vi

The ability to automatically indent code is indispensable when
editing files containing s-expression-based code such as Racket,
Common Lisp, Scheme, LFE, ART*Enterprise, and other Lisps.

The text editor family vi provides the option `lisp`, which in
conjunction with the options `autoindent` and `showmatch`
provides a form of Lisp indenting, but except in the improved vi
clones Vim and Neovim, this support is poor in at least two
respects:

1. escaped parentheses and double-quotes are not treated
   correctly; and

2. all head-words are treated identically.

Even the redoubtable Vim, which has improved its Lisp editing
support over the years, and provides the `lispwords` option,
continues to fail in link:vim-indent-error.lisp[strange ways].

Fortunately, both vi and Vim let you delegate the responsibility
for indenting such code to an external filter program of your
choosing.  I provide here four such filtering scripts:
link:scmindent.rkt[] written in Racket, link:lispindent.lisp[] in
Common Lisp, link:scmindent.lua in Lua, and link:scmindent.js[]
in JavaScript.

For more details, please see
https://ds26gte.github.io/scmindent/index.html.
